name: SETUP, TEST, BUILD & DEPLOY
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - master
      - 'release/**'
jobs:
  Setup-Test-Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Event Name
        run: echo "GitHub Event Name = $GITHUB_EVENT_NAME"
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "Checked out branch $GITHUB_REF"
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.14.0'
      - name: Install dependencies
        run: npm ci
      - name: Create working environment dev file skeleton
        uses: canastro/copy-file-action@master
        with:
          source: 'src/environments/environment.template.ts'
          target: 'src/environments/environment.ts'
      - name: Create working environment prod file skeleton
        uses: canastro/copy-file-action@master
        with:
          source: 'src/environments/environment.prod.template.ts'
          target: 'src/environments/environment.prod.ts'
      - name: Populate COMMON secrets into working environment fileS
        env:
          GTM_ID: ${{ secrets.GTM_ID }}
        run: |
          sed -i "s|gtmId: ''|gtmId: '$GTM_ID'|g" src/environments/environment.ts
          sed -i "s|gtmId: ''|gtmId: '$GTM_ID'|g" src/environments/environment.prod.ts
      - name: Run unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
      - name: Install Cypress
        run: npx cypress install
      - name: Run all E2E tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npm run start
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 120
          browser: chrome
          headless: true
          spec: cypress/integration/**/*.spec.ts
      - name: Build dev
        if: ${{ github.ref != 'refs/heads/master' }}
        run: npm run build
      - name: Build prod
        if: ${{ github.ref == 'refs/heads/master' }}
        run: npm run buildprod
      - name: Sleep for 5s
        uses: juliangruber/sleep-action@v1
        with:
          time: 5s
      - name: Deploy dev
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: '${{ secrets.FTP_HOST_DEV }}'
          username: '${{ secrets.FTP_USERNAME_DEV }}'
          password: '${{ secrets.FTP_PASSWORD_DEV }}'
          local-dir: './dist/blackswanarchery/'
          server-dir: '${{ secrets.FTP_DIR_DEV }}'
          dangerous-clean-slate: true
      - name: Deploy prod
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: '${{ secrets.FTP_HOST_PROD }}'
          username: '${{ secrets.FTP_USERNAME_PROD }}'
          password: '${{ secrets.FTP_PASSWORD_PROD }}'
          local-dir: './dist/blackswanarchery/'
          server-dir: '${{ secrets.FTP_DIR_PROD }}'
          dangerous-clean-slate: true
